version: "3.8"
services:
 db:
  image: mysql:8
  volumes:
   - db_data:/var/lib/mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD_FILE: /run/secrets/wp-root-pass
   MYSQL_DATABASE_FILE: /run/secrets/wp-db
   MYSQL_USER_FILE: /run/secrets/wp-user
   MYSQL_PASSWORD_FILE: /run/secrets/wp-user-pass
  secrets:
    - wp-root-pass
    - wp-user-pass
    - wp-db
    - wp-user
 wordpress:
  depends_on:
   - db
  image: wordpress:6
  ports:
   - "8000:80"
  restart: always
  environment:
   WORDPRESS_DB_HOST: db:3306
   WORDPRESS_DB_USER_FILE: /run/secrets/wp-user
   WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wp-user-pass
   WORDPRESS_DB_NAME_FILE: /run/secrets/wp-db
  secrets:
    - wp-user-pass
    - wp-db
    - wp-user
secrets:
  wp-root-pass:
    external: true
  wp-user-pass:
    external: true
  wp-user:
    external: true
  wp-db:
    external: true
volumes:
 db_data: {}
